/**
 * Regression coverage for the generated-file detector that drives
 * symbol-disambiguation down-ranking. Locked here because the suffix
 * list is a contract: if a future edit drops `.pb.go`, the cosmos-sdk
 * trace endpoint regresses to the gRPC stub.
 *
 * The content-header half (#1500) is a second contract: the marker table is
 * precision-first, because a false positive silently demotes hand-written
 * code in EVERY ranking path.
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import {
  isGeneratedFile,
  hasGeneratedHeader,
  detectGeneratedFile,
} from '../src/extraction/generated-detection';

describe('isGeneratedFile', () => {
  it('classifies Go protobuf / gRPC / pulsar / mock outputs as generated', () => {
    expect(isGeneratedFile('api/cosmos/bank/v1beta1/tx_grpc.pb.go')).toBe(true);
    expect(isGeneratedFile('x/bank/types/tx.pb.go')).toBe(true);
    expect(isGeneratedFile('api/cosmos/bank/v1beta1/tx.pulsar.go')).toBe(true);
    expect(isGeneratedFile('x/auth/testutil/expected_keepers_mocks.go')).toBe(true);
    expect(isGeneratedFile('internal/foo_mock.go')).toBe(true);
    expect(isGeneratedFile('mock_keeper.go')).toBe(true);
  });

  it('does not flag the hand-written keeper as generated', () => {
    expect(isGeneratedFile('x/bank/keeper/msg_server.go')).toBe(false);
    expect(isGeneratedFile('x/bank/keeper/send.go')).toBe(false);
  });

  it('catches common cross-language codegen suffixes', () => {
    expect(isGeneratedFile('app/foo.generated.ts')).toBe(true);
    expect(isGeneratedFile('app/foo.generated.tsx')).toBe(true);
    expect(isGeneratedFile('proto/bar_pb2.py')).toBe(true);
    expect(isGeneratedFile('proto/bar_pb2_grpc.py')).toBe(true);
    expect(isGeneratedFile('lib/baz.pb.cc')).toBe(true);
    expect(isGeneratedFile('lib/baz.pb.h')).toBe(true);
    expect(isGeneratedFile('lib/quux.g.dart')).toBe(true);
    expect(isGeneratedFile('lib/quux.freezed.dart')).toBe(true);
  });

  it('leaves ordinary source files alone', () => {
    expect(isGeneratedFile('src/index.ts')).toBe(false);
    expect(isGeneratedFile('src/components/Foo.tsx')).toBe(false);
    expect(isGeneratedFile('lib/main.dart')).toBe(false);
    expect(isGeneratedFile('cmd/server/main.go')).toBe(false);
    expect(isGeneratedFile('app/db.py')).toBe(false);
  });
});

describe('hasGeneratedHeader — per-marker coverage (#1500)', () => {
  const GENERATED: ReadonlyArray<[string, string]> = [
    [
      'Go — ordinary filename, banner below the package clause',
      'package payroll\n\n// Code generated by fkit. DO NOT EDIT.\n\nimport "context"\n\nfunc CreatePayroll(ctx context.Context) error { return nil }\n',
    ],
    [
      'Go — protoc-gen-go',
      '// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n//   protoc-gen-go v1.28.0\n\npackage pb\n',
    ],
    [
      'Go — banner under build tags',
      '//go:build !windows\n// +build !windows\n\n// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n',
    ],
    [
      'protoc — Java banner',
      '// Generated by the protocol buffer compiler.  DO NOT EDIT!\n// source: foo.proto\n\npackage com.example;\n',
    ],
    [
      'C# — Roslyn <auto-generated> block',
      '//------------------------------------------------------------------------------\n// <auto-generated>\n//     This code was generated by a tool.\n// </auto-generated>\n//------------------------------------------------------------------------------\n',
    ],
    ['C# — EF self-closing <auto-generated />', '// <auto-generated />\nusing System;\n'],
    [
      'JS — Meta/Relay @generated',
      '/**\n * @generated SignedSource<<0123456789abcdef0123456789abcdef>>\n * @flow\n */\n',
    ],
    [
      'TS — protobuf-es / Buf @generated',
      '// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"\n// @generated from file foo.proto (package example, syntax proto3)\n',
    ],
    [
      'OpenAPI Generator',
      '/*\n * Pet Store API\n *\n * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).\n * Do not edit the class manually.\n */\n',
    ],
    [
      'Wrangler — Generated by Wrangler by running',
      '/* eslint-disable */\n// Generated by Wrangler by running `wrangler types` (hash: adcfde101dd7d9077590b6b39d3eaf8d)\n',
    ],
    [
      'banner inside a block comment',
      '/*\n   Code generated by ent. DO NOT EDIT.\n*/\npackage ent\n',
    ],
    [
      'Python module docstring',
      '"""Generated by the protocol buffer compiler.  DO NOT EDIT!"""\nimport sys\n',
    ],
    ['YAML/shell # comment', '# This file is generated by kustomize. Do not edit.\napiVersion: v1\n'],
    ['SQL -- comment', '-- Code generated by sqlc. DO NOT EDIT.\nCREATE TABLE foo (id INT);\n'],
  ];

  it.each(GENERATED)('flags: %s', (_label, source) => {
    expect(hasGeneratedHeader(source)).toBe(true);
  });

  const HAND_WRITTEN: ReadonlyArray<[string, string]> = [
    [
      'ordinary Go source',
      'package keeper\n\nimport "context"\n\n// SendCoins moves coins between accounts.\nfunc (k Keeper) SendCoins(ctx context.Context) error { return nil }\n',
    ],
    [
      "a generator's own source, which merely talks about generating",
      '// This package generates SQL migrations from the schema.\n// The generated output lives under db/migrations.\npackage gen\n',
    ],
    [
      'prose using "automatically generated" without naming a tool',
      '"""Report builder.\n\nThe summary table is automatically generated at runtime from the\nrows below; callers should not edit it in place.\n"""\n',
    ],
    [
      'banner as a string constant in the BODY',
      'package main\n\n// Package main implements the fkit CRUD generator.\n\nimport "fmt"\n\nfunc header() string {\n\treturn "// Code generated by fkit. DO NOT EDIT."\n}\n',
    ],
    ['email containing @generated', '// Contact: build@generated.example.com for issues.\npackage main\n'],
    ['DO NOT EDIT with no generation claim', '// DO NOT EDIT THIS FILE BY HAND — run `make fmt` instead.\npackage main\n'],
    [
      'bare "generated by" with no reproduction command',
      '// The table below is generated by the build at runtime.\npackage main\n',
    ],
    ['empty file', ''],
  ];

  it.each(HAND_WRITTEN)('does not flag: %s', (_label, source) => {
    expect(hasGeneratedHeader(source)).toBe(false);
  });

  it('only looks at the header — a banner buried 80 lines down is not a banner', () => {
    const filler = Array.from({ length: 80 }, (_, i) => `// filler line ${i}`).join('\n');
    expect(hasGeneratedHeader(`${filler}\n// Code generated by foo. DO NOT EDIT.\npackage main\n`)).toBe(false);
    const shortFiller = Array.from({ length: 20 }, (_, i) => `// filler line ${i}`).join('\n');
    expect(hasGeneratedHeader(`${shortFiller}\n// Code generated by foo. DO NOT EDIT.\npackage main\n`)).toBe(true);
  });

  it('requires a comment line — the same words in executable code are not a banner', () => {
    expect(hasGeneratedHeader('const banner = "Code generated by tool. DO NOT EDIT.";\n')).toBe(false);
  });

  it('does not classify the detector module itself', () => {
    const self = fs.readFileSync(
      path.join(__dirname, '..', 'src', 'extraction', 'generated-detection.ts'),
      'utf-8',
    );
    expect(hasGeneratedHeader(self)).toBe(false);
  });
});

describe('detectGeneratedFile — union of path + content', () => {
  it('is true when either signal fires', () => {
    expect(detectGeneratedFile('x/bank/types/tx.pb.go', 'package pb\n')).toBe(true);
    expect(
      detectGeneratedFile(
        'internal/payroll.go',
        '// Code generated by fkit. DO NOT EDIT.\npackage payroll\n',
      ),
    ).toBe(true);
  });

  it('is false when neither signal fires', () => {
    expect(
      detectGeneratedFile('x/bank/keeper/send.go', 'package keeper\n\nfunc Send() {}\n'),
    ).toBe(false);
  });
});
